/* ============================================================================
   Import-ArcherLdapGroups.sql
   Archer LDAP Group Migration (SQL-Only Sub-Project)

   PURPOSE:
     Imports LDAP group placeholders into the TARGET Archer instance database as
     local groups with the EXACT source GUIDs (ldap_config_id = NULL,
     distinguished_name = NULL).

     This enables Archer packages containing LDAP group authorizations to
     auto-map and install successfully without requiring active LDAP sync.

   REQUIREMENTS:
     - Run against the TARGET Archer instance database in SSMS or sqlcmd.
     - Permissions: db_datawriter, db_owner, or sysadmin (preflight-guarded).

   SAFETY:
     - Idempotent: safe to run multiple times without duplicating groups.
     - Auth & Wrong-Database guards abort BEFORE any write.
     - Does not overwrite or delete existing groups.
     - Bypasses LDAP sync requirement by creating offline local placeholders.
   ============================================================================ */

SET NOCOUNT ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO

-- 1. Preflight Auth & Permissions
DECLARE @login SYSNAME = SUSER_SNAME();
DECLARE @db SYSNAME = DB_NAME();
DECLARE @is_owner INT = ISNULL(IS_MEMBER('db_owner'), 0);
DECLARE @can_write INT = ISNULL(IS_MEMBER('db_datawriter'), 0);
DECLARE @is_sysadmin INT = ISNULL(IS_SRVROLEMEMBER('sysadmin'), 0);

PRINT '============================================================================';
PRINT ' ARCHER LDAP GROUP IMPORT (TARGET DATABASE: ' + DB_NAME() + ')';
PRINT ' Current Login: ' + @login;
PRINT '============================================================================';

IF (@is_owner <> 1 AND @can_write <> 1 AND @is_sysadmin <> 1)
BEGIN
    RAISERROR('AUTH FAILED: Login [%s] requires db_datawriter, db_owner, or sysadmin on [%s]. No changes made.', 16, 1, @login, @db);
    SET NOEXEC ON;
    RETURN;
END

-- 2. Preflight Target Database Name (uses @db declared above)
IF @db IN ('master', 'model', 'msdb', 'tempdb')
BEGIN
    RAISERROR('DATABASE CHECK FAILED: Connected to system database [%s]. Point SSMS at the TARGET Archer instance database.', 16, 1, @db);
    SET NOEXEC ON;
    RETURN;
END

IF OBJECT_ID('dbo.tblGroup', 'U') IS NULL
BEGIN
    RAISERROR('SCHEMA CHECK FAILED: dbo.tblGroup not found in [%s]. Is this a valid Archer instance database?', 16, 1, @db);
    SET NOEXEC ON;
    RETURN;
END
GO

-- 3. Staging Table: Paste Exported Groups Here
IF OBJECT_ID('tempdb..#Src') IS NOT NULL DROP TABLE #Src;
CREATE TABLE #Src (
    group_name NVARCHAR(500) NOT NULL, 
    guid UNIQUEIDENTIFIER NOT NULL
);

/* ----------------------------------------------------------------------------
   >>> PASTE ROWS FROM Export-ArcherLdapGroups.sql BELOW THIS LINE <<<
   ---------------------------------------------------------------------------- */

-- EXAMPLE PLACEHOLDERS (fictional GUIDs — replace or append real rows):
-- INSERT INTO #Src VALUES (N'Example Finance Group', 'AAAAAAAA-AAAA-4AAA-8AAA-AAAAAAAAAAAA');
-- INSERT INTO #Src VALUES (N'Example HR Group', 'BBBBBBBB-BBBB-4BBB-8BBB-BBBBBBBBBBBB');
-- INSERT INTO #Src VALUES (N'Example-Entity-Group', 'CCCCCCCC-CCCC-4CCC-8CCC-CCCCCCCCCCCC');

/* ----------------------------------------------------------------------------
   >>> END OF PASTED ROWS <<<
   ---------------------------------------------------------------------------- */

DECLARE @src_count INT = (SELECT COUNT(*) FROM #Src);
IF @src_count = 0
BEGIN
    PRINT 'NOTICE: #Src table is empty. Paste rows generated by Export-ArcherLdapGroups.sql above.';
    SET NOEXEC ON;
    RETURN;
END
PRINT 'Payload loaded: ' + CAST(@src_count AS VARCHAR(10)) + ' group(s) staged.';
PRINT '';

-- 4. Pre-Import Analysis: Matched vs Missing
PRINT '----------------------------------------------------------------------------';
PRINT '--- PRE-IMPORT ANALYSIS: MATCHED VS MISSING                              ---';
PRINT '----------------------------------------------------------------------------';

SELECT 
    s.group_name AS [Source_GroupName],
    s.guid AS [Source_GUID],
    g.group_id AS [Target_GroupId],
    g.group_name AS [Target_GroupName],
    CASE 
        WHEN g.group_id IS NULL THEN 'MISSING (Will be inserted)'
        WHEN g.group_name <> s.group_name THEN 'MATCHED BY GUID (Name differs in target)'
        ELSE 'MATCHED (Already exists)'
    END AS [Status]
FROM #Src s
LEFT JOIN dbo.tblGroup g ON g.guid = s.guid;

-- Check for Name Collisions (Same Name, Different GUID)
DECLARE @conflict_count INT;
SELECT @conflict_count = COUNT(*)
FROM #Src s
JOIN dbo.tblGroup g ON g.group_name = s.group_name
WHERE g.guid <> s.guid;

IF @conflict_count > 0
BEGIN
    PRINT '';
    PRINT 'WARNING: ' + CAST(@conflict_count AS VARCHAR(10)) + ' name collision(s) detected:';
    SELECT 
        s.group_name AS [ConflictingName],
        s.guid AS [Source_GUID_Expected],
        g.guid AS [Target_GUID_Existing],
        g.group_id AS [Target_GroupId]
    FROM #Src s
    JOIN dbo.tblGroup g ON g.group_name = s.group_name
    WHERE g.guid <> s.guid;
    PRINT 'NOTE: These groups will be skipped to protect existing target groups.';
END
PRINT '';

-- 5. Dynamic Audit Login Resolution
DECLARE @admin_login INT = 2;
IF NOT EXISTS (SELECT 1 FROM dbo.tblUser WHERE user_id = @admin_login)
BEGIN
    -- NOTE: zero-row SELECT leaves @admin_login unchanged, so NULL it first;
    -- otherwise the IS NULL fallback below can never fire.
    SET @admin_login = NULL;
    SELECT TOP 1 @admin_login = user_id FROM dbo.tblUser WHERE user_username = 'sysadmin';
    IF @admin_login IS NULL
        SELECT TOP 1 @admin_login = user_id FROM dbo.tblUser ORDER BY user_id ASC;
END
PRINT 'Audit Login ID to use: ' + CAST(@admin_login AS VARCHAR(10));

-- 6. Insert Missing Groups
PRINT '----------------------------------------------------------------------------';
PRINT '--- INSERTING MISSING PLACEHOLDER GROUPS                                        ---';
PRINT '----------------------------------------------------------------------------';

INSERT INTO dbo.tblGroup
    (group_name, group_desc, create_date, create_login, update_date, update_login,
     everyone, guid, [system], distinguished_name, ldap_config_id)
SELECT 
    s.group_name, 
    N'Migrated LDAP placeholder group for offline packaging', 
    GETDATE(), 
    @admin_login, 
    GETDATE(), 
    @admin_login, 
    0, 
    s.guid, 
    0, 
    NULL, 
    NULL
FROM #Src s
WHERE NOT EXISTS (SELECT 1 FROM dbo.tblGroup g WHERE g.guid = s.guid)
  AND NOT EXISTS (SELECT 1 FROM dbo.tblGroup g2 WHERE g2.group_name = s.group_name AND g2.guid <> s.guid);

DECLARE @inserted_count INT = @@ROWCOUNT;
PRINT 'Newly Inserted Groups: ' + CAST(@inserted_count AS VARCHAR(10));
PRINT '';

-- 7. Verification Check (confirms every source GUID now exists in dbo.tblGroup,
--    which is what the package installer matches on)
PRINT '----------------------------------------------------------------------------';
PRINT '--- VERIFICATION (package installer GUID match check)                  ---';
PRINT '----------------------------------------------------------------------------';

DECLARE @matched_total INT;
SELECT @matched_total = COUNT(*)
FROM dbo.tblGroup g
JOIN #Src s ON s.guid = g.guid;

PRINT 'Total Required Groups: ' + CAST(@src_count AS VARCHAR(10));
PRINT 'Total Matched in DB  : ' + CAST(@matched_total AS VARCHAR(10));

IF @matched_total = @src_count
BEGIN
    PRINT '';
    PRINT 'SUCCESS: All groups are present in the target database.';
    PRINT 'You may now proceed with the Archer Application Package installation.';
END
ELSE
BEGIN
    PRINT '';
    PRINT 'WARNING: ' + CAST((@src_count - @matched_total) AS VARCHAR(10)) + ' group(s) could not be matched.';
    PRINT 'Review the name collisions above before package install.';
END
GO

SET NOEXEC OFF;
GO
